// Contenido de ficción para el escenario. Ninguna ficha describe personal o seguridad reales.
// Los correos .invalid y las extensiones internas son atrezzo y no se deben usar para contactar.
const failure='No puedo dar ese dato por contrastado. Anota la duda y solicita a Control otra fuente antes de volver a revisar esta ficha.';
function file(id,title,keys,skills,difficulty,success,improvement,source){
 return {id,title,keys,source,answer:'Hay una ficha pendiente de contraste: '+title+'.',check:{skill:skills[0],skills,difficulty,success,improvement,failure}};
}
const staff=[
 ['aurora','Aurora Cebollero','directora',['directora','direccion','aurora','cebollero'],'direccion','201','Autoriza permisos de uso del conjunto y recibe informes de la exposición. Exige solicitudes por escrito.','Coordina a Nieves Aznárez y a Nuria Calvo. Respeta el criterio de Berta Lerín sobre conservación.','No firma una excepción que no lleve responsable identificado.'],
 ['nieves','Nieves Aznárez','coordinadora de visitantes',['nieves','aznarez','visitantes','taquilla'],'visitantes','202','Lleva reservas, grupos y reclamaciones. Puede confirmar aforos previstos, no permisos de servicio.','Trabaja estrechamente con Celia Monreal. Consulta a Aurora antes de admitir grupos fuera de programa.','Prefiere resolver malentendidos discretamente para evitar una queja formal.'],
 ['fermin','Fermín Latorre','responsable de mantenimiento',['fermin','latorre','jefe de mantenimiento','responsable de mantenimiento','mantenimiento'],'mantenimiento','211','Gestiona incidencias del edificio; las revisiones de electrónica se encargan a Nordia.','Es el tío de Julián Berges. Se enfada cuando Dani Cosculluela cambia un montaje sin avisarle.','Guarda copias de partes de reparación porque no confía en los resúmenes de los proveedores.'],
 ['julian','Julián Berges','auxiliar de mantenimiento',['julian','berges','auxiliar de mantenimiento'],'servicios','212','Recibe material de mantenimiento y tramita albaranes; no autoriza acceso a las salas.','Sobrino de Fermín. Tiene pagos domésticos atrasados y busca horas extra, pero no ha aceptado ningún encargo irregular.','Le preocupa quedar como poco fiable ante su tío; un trato respetuoso ayuda más que una amenaza.'],
 ['celia','Celia Monreal','guía principal',['celia','monreal','guia principal','guias'],'visitas','203','Conoce el discurso de la exposición y las reservas de visitas. Canaliza cambios de grupo a través de Nieves.','Amiga de Leire Solano desde un trabajo anterior. Discrepa con Amaya sobre cuánto simplificar las cartelas.','Suele recordar a quien pregunta por una obra concreta, más que a quien pregunta solo por el edificio.'],
 ['amaya','Amaya Ferrer Loscos','comisaria',['amaya','ferrer','loscos','comisaria'],'comisariado','221','Responsable del catálogo y de la relación con los prestadores. Contacto profesional: amaya.ferrer@exposicion-veruela.invalid.','Trabajó con Berta Lerín en dos muestras anteriores. Mantiene una disputa presupuestaria con Dani por el desmontaje.','Quiere cerrar el 31 de diciembre sin incidencias y dejar un inventario impecable.'],
 ['berta','Berta Lerín','conservadora',['berta','lerin','conservadora','conservacion'],'conservacion','222','Autoriza las condiciones de manipulación y revisa los informes de estado. Contacto profesional: berta.lerin@exposicion-veruela.invalid.','Confía en el criterio de Fermín sobre el edificio. Choca con Dani cuando se acortan plazos de embalaje.','Defiende que V02 se conserve con marco y trasera; no acepta promesas verbales sobre su protección.'],
 ['dani','Dani Cosculluela','coordinador de montaje',['dani','cosculluela','montaje'],'montaje','223','Coordina a Trama Museografía y los bultos previstos para el desmontaje posterior al cierre.','Amaya le exige justificar los costes; Berta rechaza sus cambios cuando no incluyen conservación.','Trama le comunica cualquier cambio de personal antes de confirmarlo a la dirección.'],
 ['iria','Iria Mena','mediadora cultural',['iria','mena','mediacion'],'mediacion','204','Lleva talleres y actividades divulgativas. No forma parte de la contrata de seguridad.','Celia revisa con ella los materiales de las visitas. Es amiga de Inés, la investigadora alojada.','Puede aclarar el calendario cultural si se le pregunta por una actividad concreta.'],
 ['ramon','Ramón Escartín','enlace del ala de alojamiento',['ramon','escartin','enlace hotelero'],'alojamiento','301','Coordina las estancias vinculadas a la exposición y la relación con recepción.','Trabaja con Loreto Chueca; mantiene separadas las listas de alojados y las acreditaciones de la exposición.','Una reserva de habitación no equivale a permiso para entrar en las salas cerradas.'],
 ['loreto','Loreto Chueca','responsable de recepción',['loreto','chueca','recepcionista','recepcion'],'recepcion','302','Custodia las reservas y recibe mensajes para los alojados a través de recepción.','Informa a Ramón sobre cambios de estancia y a Nieves sobre visitas solicitadas por huéspedes.','No entrega el directorio privado: admite dejar un mensaje identificado.'],
 ['nuria','Nuria Calvo','coordinadora de vigilancia',['nuria','calvo','coordinadora de vigilancia','jefa de seguridad'],'vigilancia','231','Gestiona los partes y la asignación de servicio. Las consultas se tramitan por coordinación, no por teléfonos particulares.','Confía en Sabino para los cierres y exige a Leire que registre las incidencias con visitantes.','Tras un desacuerdo pide que todo quede en un parte; no negocia excepciones por amistad.'],
 ['sabino','Sabino Gadea','vigilante nocturno',['sabino','gadea','guardia de noche','guardia nocturno','vigilante nocturno'],'coordinacion-nocturna','232','Está asignado al servicio nocturno del 31 de diciembre. Su contacto pasa por coordinación; no consta móvil personal.','Conoce a Fermín desde hace años. Nuria valora que comunique las incidencias antes de actuar por su cuenta.','Prefiere pedir apoyo y documentar una situación dudosa antes que enfrentarse a alguien.'],
 ['leire','Leire Solano','vigilante de atención al público',['leire','solano','vigilante de dia'],'coordinacion-diurna','233','Presta servicio durante la apertura; atiende incidencias del circuito expositivo.','Amiga de Celia Monreal. La amistad no le permite autorizar accesos ni omitir un parte.','Recuerda las conversaciones relacionadas con el montaje y la conservación.']
];
const providers=[
 ['trama','Trama Museografía SL',['trama','museografia','peanas','paneles'],'Lucía Royo','coordinacion@trama-museografia.invalid','Peanas, paneles y embalajes. Coordinación: Dani Cosculluela.','El 31 de diciembre solo tiene prevista la confirmación del inventario de embalajes. El desmontaje comienza después del cierre de la muestra, ya en enero; la franja concreta sigue pendiente.','Lucía exige que Dani confirme cualquier sustitución de operario.'],
 ['nordia','Nordia Sistemas Ibérica',['nordia','instalador','contrata tecnica'],'Iván Serrano','servicio@nordia-sistemas.invalid','Mantenimiento de vídeo y detección; relación técnica con Fermín y Nuria.','La orden de mantenimiento no incluye una desconexión general por fin de exposición. No consta intervención presencial programada para la noche del 31.','Iván entrega informes a Nuria y copias de mantenimiento a Fermín; no decide quién accede al recinto.'],
 ['brillo','Brillo Norte',['brillo','empresa de limpieza','limpieza'],'Sonia Perales','turnos@brillo-norte.invalid','Limpieza de espacios de público; coordinación de servicio con Nieves.','La hoja del 31 contempla una revisión al terminar la visita pública. Una incidencia requiere autorización antes de cambiar el servicio.','Sonia no acepta que otro contratista amplíe su encargo por una petición verbal.'],
 ['ribera','Ribera Frío',['ribera','catering','comida','bebida'],'Álex Cebrián','eventos@ribera-frio.invalid','Catering de actos culturales; contacto con Iria Mena.','No figura una fiesta de Nochevieja abierta al público en el programa de clausura. Cualquier servicio adicional tendría que constar en una orden nueva.','Álex y Dani han compartido montajes; no pertenecen a la misma empresa.'],
 ['jardin','Moncayo Jardín',['moncayo jardin','jardineria','jardinero'],'Héctor Sanz','pedidos@moncayo-jardin.invalid','Suministros de jardinería; enlace con mantenimiento.','Su orden está limitada a espacios exteriores. No incluye trabajos dentro de la exposición ni una entrega nocturna el 31.','Héctor pide siempre la firma de recepción del encargado, aunque conozca al resto del personal.'],
 ['archivo','Archivo Claro',['archivo claro','reprografia','catalogo','catalogos'],'Alicia Soria','edicion@archivo-claro.invalid','Reprografía y pruebas del catálogo; trabaja con Amaya.','Debe entregar la relación de erratas antes del cierre de la exposición. Su documentación editorial no contiene el esquema de seguridad.','Alicia comparte consultas de catálogo con Inés Valcárcel, la investigadora alojada.'],
 ['cierzo','Cierzo Transporte de Arte',['cierzo transporte','transportista','transporte de arte'],'Pablo Narvión','coordinacion@cierzo-arte.invalid','Transporte especializado posterior a la clausura; coordinación con Berta y Dani.','No hay retirada de piezas prevista antes de que finalice la exposición el 31 de diciembre. La expedición será posterior; Control confirmará la fecha.','El Mecenas mantiene el encargo dentro del recinto: no contempla actuar sobre un transporte en marcha.']
];
const residents=[
 ['ines','Inés Valcárcel',['ines','valcarcel','investigadora alojada'],'Investigadora del catálogo, alojada en el ala de huéspedes hasta el 2 de enero.','Mensajes a través de recepción, extensión 311; ines.valcarcel@alojamiento-veruela.invalid.','Amiga de Iria Mena y colaboradora de Alicia Soria. Trabaja con fuentes del catálogo, no con la documentación de seguridad.'],
 ['joel','Joel Rivas',['joel','rivas','fotografo alojado'],'Fotógrafo encargado del registro de la muestra, con estancia hasta el 1 de enero.','Mensajes a través de recepción, extensión 312; joel.rivas@alojamiento-veruela.invalid.','Dani contrata su trabajo y Berta valida cómo documenta las piezas. Ha discutido con Dani por los plazos de entrega.'],
 ['elvira','Elvira Pardo',['elvira','pardo','cuidadora residente','residente permanente'],'Cuidadora residente de los espacios de alojamiento; ocupa una dependencia de servicio.','Mensajes a través de recepción, extensión 313; elvira.pardo@alojamiento-veruela.invalid.','Ramón organiza sus encargos y Fermín resuelve las incidencias de su vivienda. No lleva las llaves de la exposición.'],
 ['pilar','Pilar Uceda',['pilar','uceda','archivera alojada'],'Archivera invitada para revisar documentación de la colección; estancia hasta el 2 de enero.','Mensajes a través de recepción, extensión 314; pilar.uceda@alojamiento-veruela.invalid.','Amaya solicitó su visita. Respeta a Inés, aunque discrepan sobre la atribución de dos documentos del catálogo.']
];
export const INTEL=[
 file('personal-directorio','Directorio del personal',['personal','empleados','plantilla','quien trabaja','nombres del personal'],['Informática','Buscar libros'],'regular',staff.map(p=>p[1]+' — '+p[2]).join('\n'),'Puedes pedir la ficha de una persona por su nombre o función para contrastar contacto y relaciones.','Directorio de coordinación de la exposición'),
 ...staff.map(p=>file('persona-'+p[0],'Personal · '+p[2],p[3],['Informática','Buscar libros'],'regular',p[1]+' · '+p[2]+'. '+p[6]+'\nCanal profesional: '+p[4]+'@exposicion-veruela.invalid · extensión interna '+p[5]+'.\nRelaciones: '+p[7],p[8],'Ficha de coordinación '+p[1])),
 file('relaciones-personal','Relaciones entre el personal',['relaciones','relacion','se conocen','amigos','familia','parentesco','disputa','enemistad','motivos','motivaciones'],['Psicología'],'dificil','Amaya y Berta han trabajado juntas; las dos discuten con Dani por plazos y conservación. Fermín es tío de Julián. Celia y Leire son amigas. Ramón y Loreto separan las reservas de alojamiento de las acreditaciones de exposición.','Julián busca horas extra por deudas domésticas. Berta prioriza la integridad de las obras; Amaya, el cierre sin incidencias; Nuria, la trazabilidad de los partes. Ninguno ha ofrecido colaborar con el encargo.','Cruce de entrevistas y correspondencia'),
 file('proveedores-directorio','Directorio de proveedores',['proveedor','proveedores','contratas','empresas del evento'],['Contabilidad','Informática'],'regular',providers.map(p=>p[1]+' — '+p[3]+' · '+p[4]).join('\n'),'Pide la ficha de una empresa para contrastar su función, relaciones y orden de servicio del 31 de diciembre.','Relación administrativa de contratistas'),
 ...providers.map((p,i)=>file('proveedor-'+p[0],'Proveedor · '+['Museografía','Mantenimiento electrónico','Limpieza','Catering','Jardinería','Catálogo','Transporte de arte'][i],p[2],['Contabilidad','Informática'],'dificil',p[1]+'. Responsable: '+p[3]+'. Contacto: '+p[4]+'.\n'+p[5]+'\n'+p[6],p[7],'Orden y albaranes de '+p[1])),
 file('residentes-directorio','Personas alojadas y residentes',['habitantes','residentes','alojados','huespedes','quien vive','quienes viven','monjes','frailes'],['Buscar libros','Informática'],'regular','La relación del 31 de diciembre incluye a Inés Valcárcel, Joel Rivas, Elvira Pardo y Pilar Uceda. Sus fichas distinguen huéspedes y personal residente. No consta una comunidad religiosa residente en esta relación.','Las estancias son gestionadas por Ramón Escartín y Loreto Chueca. La relación de alojamiento no acredita la posición de nadie en cada momento.','Relación de estancias del 31 de diciembre'),
 ...residents.map((p,i)=>file('residente-'+p[0],'Alojamiento · expediente '+(i+1),p[2],['Buscar libros','Psicología'],'regular',p[1]+'. '+p[3]+'\n'+p[4]+'\n'+p[5],'La reserva confirma la estancia, no sus movimientos durante la noche. Cualquier presencia puntual sigue pendiente de contraste.','Ficha de estancia '+p[1])),
 file('video-tecnico','Documentación técnica de vídeo',['modelo de camara','modelos de camaras','caracteristicas de camaras','mirador','grabador','retencion','resolucion','poe','cctv tecnico'],['Electrónica','Informática'],'dificil','El inventario contiene diez Mirador M12-IP4: cámaras fijas IP de 4 MP, óptica de 2,8 mm, alimentación PoE y modo día/noche. No registran audio. El grabador Mirador Archivo-16 tiene dieciséis canales y retención documental prevista de catorce días.','La retención es una previsión de capacidad, no una prueba de que todos los archivos estén disponibles. El vídeo y las alarmas usan registros diferenciados; el modelo 3D no calcula oclusiones reales.','Inventario audiovisual del escenario'),
 file('alarmas-tecnico','Arquitectura de alarmas',['modelos de alarmas','central de alarmas','centralita','centinela','onix','arca 4','faro central','sistemas de alarma'],['Electrónica','Informática'],'dificil','ONIX Arca 4 reúne los eventos de seis avisos A01–A06. Centinela 24 separa las particiones de sala. Faro Central recibe las incidencias de comunicación. Los registros distinguen apertura, presencia, manipulación e incidencias del propio sistema.','El cierre de la exposición no equivale a apagar los avisos: el 31 de diciembre las zonas continúan bajo su procedimiento de cierre. Un aviso de vitrina no es una simple indicación visual local.','Memoria de integración del escenario'),
 file('turno-nochevieja','Asignación de vigilancia del 31 de diciembre',['quien vigila el 31','turno del 31','guardia en nochevieja','guardias en nochevieja','vigilancia de nochevieja'],['Buscar libros','Descubrir'],'dificil','La asignación nocturna del 31 de diciembre corresponde a Sabino Gadea, bajo coordinación de Nuria Calvo. El expediente mantiene un vigilante nocturno y las rondas orientativas del dossier.','La asignación no certifica recorridos ni minutos libres. Las incidencias de clausura pueden alterar la rutina.','Hoja de asignación de Nochevieja')
];
const cameraZones=['Portería','Claustro · esquina 1','Claustro · esquina 2','Claustro · esquina 3','Claustro · esquina 4','Entrada de monjes','Puerta de la Sala Capitular','Refectorio · galería','Refectorio · cocina','Plaza de la iglesia'];
for(let i=0;i<cameraZones.length;i++){
 const id='C'+String(i+1).padStart(2,'0');
 INTEL.push(file('camara-'+id.toLowerCase(),'Ficha de '+id+' · '+cameraZones[i],[id.toLowerCase()],['Electrónica','Informática'],'regular',id+' · '+cameraZones[i]+'. Mirador M12-IP4 fija, 4 MP, alimentación PoE y modo día/noche; sin audio. Canal '+(i+1)+' del grabador Archivo-16. Responsable técnico: Nordia Sistemas Ibérica.','El abanico del atlas representa una orientación aproximada. Esta ficha no demuestra cobertura completa ni confirma que un paso quede fuera de imagen.','Inventario audiovisual · '+id));
}
const alarms=[
 ['A01','Portería','Centinela C-20','Contacto magnético de apertura de hoja y señal de incidencia de carcasa.','Nuria Calvo recibe el parte; Nordia mantiene el equipo.'],
 ['A02','Puerta de la Sala Capitular','Centinela C-20','Contacto de apertura de la puerta, con registro diferenciado de la vitrina interior.','Abrir la sala y manipular la vitrina son eventos distintos.'],
 ['A03','Vitrina del relicario','Klarvit V90 / ART TAG Lumen','Supervisa apertura de vitrina, vibración y variación de carga. El expediente los trata como una protección compuesta.','Berta Lerín valida las condiciones de conservación; Nordia mantiene la electrónica. Una autorización de manipulación no se deduce de una acreditación de visitante.'],
 ['A04','Iglesia','Centinela D-24','Detector de presencia de doble tecnología, infrarrojo pasivo y microondas, asociado a la partición de la iglesia.','Su historial es independiente de la grabación de vídeo de la sala.'],
 ['A05','Refectorio','Centinela D-24','Detector de presencia de doble tecnología asociado a la partición del refectorio.','La ficha de exposición y la ficha del sensor son documentos diferentes.'],
 ['A06','Cilla / almacén','Centinela C-20','Contacto de apertura del acceso al almacén, con registro en ONIX Arca 4.','Una petición de material no constituye permiso para acceder al almacén.']
];
for(const [id,zone,model,description,detail]of alarms)INTEL.push(file('alarma-'+id.toLowerCase(),'Ficha de '+id+' · '+zone,[id.toLowerCase()],['Electrónica'],'dificil',id+' · '+zone+'. Modelo: '+model+'. '+description,detail,'Inventario de detección · '+id));

const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const has=(q,k)=>(' '+q+' ').includes(' '+norm(k)+' ');
export function findIntel(q,contextTopic){
 const byId=id=>INTEL.find(e=>e.id===id);
 const ids=[...q.matchAll(/\b([ca])\s?(0?[1-9]|10)\b/g)].map(m=>(m[1]==='c'?'camara-':'alarma-')+m[1]+m[2].padStart(2,'0'));
 if(ids.length){const entries=[...new Set(ids)].map(byId).filter(Boolean);if(entries.length>1)return {id:'aclarar-ficha',answer:'Pide una ficha cada vez: '+entries.map(e=>e.title).join('; ')+'.'};if(entries.length)return entries[0];}
 if(/\b(relacion|relaciones|parentesco|amigos|familia|se conocen|disputa|enemistad|motivaciones)\b/.test(q))return byId('relaciones-personal');
 const people=INTEL.filter(e=>/^(persona|residente|proveedor)-/.test(e.id)&&e.keys.some(k=>has(q,k)));
 if(people.length>1)return {id:'aclarar-persona',answer:'Pide una ficha cada vez: '+people.map(e=>e.title).join('; ')+'.'};
 if(people.length)return people[0];
 if(/\b(vitrina|relicario|p07)\b/.test(q)&&/\b(tecnic[a-z]*|protege|proteccion|modelo|sensor[a-z]*|alarma[a-z]*|vibracion|peso)\b/.test(q))return byId('alarma-a03');
 if(/\b(camara[a-z]*|cctv|video)\b/.test(q)&&/\b(tecnic[a-z]*|modelo[a-z]*|marca[a-z]*|tipo[a-z]*|caracteristica[a-z]*|resolucion|retencion|grabador|audio|optica|alimentacion|graban|graba|grabaciones|grabacion|grabar|guardan|almacenan)\b/.test(q))return byId('video-tecnico');
 if(/\b(alarma[a-z]*|sensor[a-z]*)\b/.test(q)&&/\b(tecnic[a-z]*|modelo[a-z]*|marca[a-z]*|tipo[a-z]*|caracteristica[a-z]*|central|funcionan|funciona|comunicaciones)\b/.test(q))return byId('alarmas-tecnico');
 const categories=INTEL.filter(e=>!e.id.startsWith('persona-')&&!e.id.startsWith('residente-')&&!e.id.startsWith('proveedor-')&&!e.id.startsWith('camara-')&&!e.id.startsWith('alarma-'));
 const match=categories.find(e=>e.keys.some(k=>has(q,k)));if(match)return match;
 if(contextTopic&&/^(y |su |sus |el contacto|el telefono|el correo)/.test(q)&&/\b(contacto|telefono|correo|email|datos|ficha)\b/.test(q))return byId(contextTopic)||null;
 return null;
}
